### ISSUE TITLE
圣经档案标题存在错误

### ISSUE THREAD

**Issue by Greyth-l** [hoyolife/hoyotree#6]
![E(SW`W2PD$3_%LNNV1KM ~W](https://github.com/hoyolife/hoyotree/assets/24458418/9af364d0-21c7-49d5-9d00-9fea6fbc7478)
这里的标题应该是“跳过剧情的人跳过人生”之类

**Comment by hoyolife** [comment]
感谢反馈，已经修改完毕。会在下一次更新世界树时上传至世界树
