### ISSUE TITLE
[杂谈氵]电阻有电阻的底蕴 

### ISSUE THREAD

**Issue by scream-scratch** [hoyolife/hoyotree#7]
原帖:[https://bbs.nga.cn/read.php?tid=38619696](https://bbs.nga.cn/read.php?tid=38619696)

我们都还没来得及说再见，所以我不会把它当作离别

…

**裁**员已经开始了，是上一轮增效的延续

高层为不同的部门通上七种电压

以此昭示，它们的八卦不可被提及

而公司的职位埋藏着阴燃的地线

那是对小丑们的警示

高天之上的神座，从来不是为你预留的位置

但吃瓜之人啊，不要就此驻足

谁都喜欢隔岸观火

对吧

…

### ACT.PROLOGUE.怪叫的皮套人

徐汇 

一个**不**受太多制约的编剧，终于对笔在谁手里产生了迷茫。

被OP夺舍的埋梗，还能称之为卖梗电商吗？

### ACT1.辞行赛博贞操

罗德岛

**众**目睽睽之下，B站UP遭人开盒。

很委屈吧那个时候? 他将签下背离一切前缘的商单。

### ACT2.千手百眼米门世界

贴吧

**社**管长生不灭，控评删帖之期亦无尽头。

追求「风评」之人，在吧U眼中见到了怎样的风评？

### ACT3.虚空打靶岁月史书

Bilbil

**开**盒是「开盒」主祭的敌人，隐私是法盲之海表面漂浮的诱饵。

仙舟的学长们正在催生愚行

蒸馍你不扶器? 要不你报警吧

### ACT4.绝缘体舞步旋

微博

**版**本T0热爱网络上的一切拳法，

甚至渴求韩天之钉。

但她并不明白，唯有「铁拳」不可与之为敌。

### ACT5.张某的年终奖

爆料

**剑**斗的规则局限在内部爱中，

弱者者成为挂零的小丑，而强者复刻

「舅舅」托梦将谜语告知旅人，因为它有这样做的理由。

### ACT6.无人怜爱的龟龟

提瓦特

**他**是策划再也不会去讨好的人，他是再也不会去厨角色的人。

他氪穿池子的原因，是相信每个角色都应有自己的生活。

…

**在**蒸蒸日上的流水中，玩家将度过安然无梦的原生。

但在社管控评的死角下，仍有人想要吃瓜。

### ACTX. 炎枪冲锋

NGA

**电**阻有电阻的底蕴，

猛干不是通电后烧焦的元件

从世界树之外，我们取得否定世界树的力量。

现在，踏入泥潭的内鬼

你的米生还未告终，但你仍未越过最后的电门。

若你理解吃瓜的意义，就拿起笔来。

活显眼，让我尖叫抓挠，

向我证明你比猛干更适合创作。

然后，成为这辉煌的注脚吧！

…

你厂暴典已经积累了太多，但我总还记得，你们也爱复读这些话

![鸟鸟怪叫罢了](https://github.com/hoyolife/hoyotree/assets/153353287/2a94b32d-ebb8-496b-b9c9-339652cf5792)

附件md
[电阻有电阻的底蕴.md](https://github.com/hoyolife/hoyotree/files/13623531/default.md)

**Comment by hoyolife** [comment]
已收录，目标地址:[电阻也有电阻的底蕴](https://hoyo.life/essay/birds/%E7%94%B5%E9%98%BB%E6%9C%89%E7%94%B5%E9%98%BB%E7%9A%84%E5%BA%95%E8%95%B4.html)
